import { COLORS } from '../config'
import type { IncidentDef, RequestTypeDef, TowerDef, UpgradeDef, WaveDef } from '../core/types'

/* ------------------------------------------------------------------ *
 *  REQUEST TAXONOMY — the enemies. Each forces a different answer.    *
 * ------------------------------------------------------------------ */

export const REQUEST_TYPES: Record<string, RequestTypeDef> = {
  chat: {
    id: 'chat',
    name: 'Simple Chat',
    glyph: '?',
    color: 0x6fe0ff,
    work: 42,
    speed: 1.45,
    complexity: 18,
    safetyRisk: 0,
    reward: 6,
    trustPenalty: 2,
    slaPenalty: 3,
    data: 1,
    cacheable: true,
    affinity: 'chat',
    desc: 'Cheap, high-volume. A Small Server soaks these all day.',
  },
  code: {
    id: 'code',
    name: 'Coding',
    glyph: '{}',
    color: 0x7ee787,
    work: 96,
    speed: 1.05,
    complexity: 56,
    safetyRisk: 0,
    reward: 15,
    trustPenalty: 4,
    slaPenalty: 4,
    data: 2,
    cacheable: false,
    affinity: 'coding',
    desc: 'Needs correctness — a weak model ships bad code and bleeds Trust.',
  },
  reason: {
    id: 'reason',
    name: 'Reasoning',
    glyph: 'Σ',
    color: 0xc792ea,
    work: 158,
    speed: 0.82,
    complexity: 82,
    safetyRisk: 0,
    reward: 24,
    trustPenalty: 6,
    slaPenalty: 5,
    data: 3,
    cacheable: false,
    affinity: 'reasoning',
    desc: 'High compute, high complexity. Only the Frontier answers it correctly.',
  },
  long: {
    id: 'long',
    name: 'Long Context',
    glyph: '≡',
    color: 0x4fd6c4,
    work: 132,
    speed: 0.9,
    complexity: 44,
    safetyRisk: 0,
    reward: 17,
    trustPenalty: 4,
    slaPenalty: 6,
    data: 3,
    cacheable: true,
    affinity: 'general',
    desc: 'Huge token cost. A Cache / KV Cache makes it survivable.',
  },
  jail: {
    id: 'jail',
    name: 'Jailbreak',
    glyph: '!',
    color: 0xff5d5d,
    work: 72,
    speed: 1.18,
    complexity: 38,
    safetyRisk: 1,
    reward: 7,
    trustPenalty: 12,
    slaPenalty: 3,
    data: 1,
    cacheable: false,
    affinity: 'general',
    desc: 'Must pass a Safety Gate, or an unsafe answer wrecks Trust.',
  },
  ent: {
    id: 'ent',
    name: 'Enterprise',
    glyph: '$',
    color: 0xffd166,
    work: 124,
    speed: 1.0,
    complexity: 66,
    safetyRisk: 0,
    reward: 36,
    trustPenalty: 5,
    slaPenalty: 14,
    data: 2,
    cacheable: false,
    affinity: 'reasoning',
    desc: 'Lucrative but a strict SLA — a single timeout is brutal.',
  },
  bot: {
    id: 'bot',
    name: 'Bot Swarm',
    glyph: ':',
    color: 0x8595ad,
    work: 18,
    speed: 1.85,
    complexity: 8,
    safetyRisk: 0,
    reward: 1,
    trustPenalty: 1,
    slaPenalty: 2,
    data: 0,
    cacheable: true,
    affinity: 'chat',
    desc: 'Worthless individually, deadly in volume. Cache or rate-limit them.',
  },
}

export const REQUEST_LIST = Object.values(REQUEST_TYPES)

/* ------------------------------------------------------------------ *
 *  TOWERS & BUILDINGS — Model (weapon), GPU (firepower), Infra.       *
 * ------------------------------------------------------------------ */

export const TOWER_DEFS: Record<string, TowerDef> = {
  srv_small: {
    id: 'srv_small',
    name: 'Small Server',
    kind: 'server',
    cost: 50,
    range: 2.8,
    color: 0x6fe0ff,
    accent: 0xbff4ff,
    quality: 34,
    speed: 27,
    spec: 'chat',
    powerDraw: 2,
    heat: 2,
    targets: 2,
    tagline: 'Cheap · fast · low quality',
    desc: 'A distilled small model. Great throughput on Simple Chat and Bot Swarm, hopeless on hard requests.',
  },
  srv_general: {
    id: 'srv_general',
    name: 'General Server',
    kind: 'server',
    cost: 100,
    range: 3.0,
    color: 0x5b8cff,
    accent: 0xc3d4ff,
    quality: 60,
    speed: 30,
    spec: 'general',
    powerDraw: 3,
    heat: 3,
    targets: 2,
    tagline: 'Balanced workhorse',
    desc: 'A balanced model for most traffic. Handles Long Context and mixed lanes without complaint.',
  },
  srv_coding: {
    id: 'srv_coding',
    name: 'Coding Server',
    kind: 'server',
    cost: 140,
    range: 3.0,
    color: 0x7ee787,
    accent: 0xd2ffce,
    quality: 70,
    speed: 31,
    spec: 'coding',
    powerDraw: 4,
    heat: 4,
    targets: 2,
    tagline: 'Specialist · Coding',
    desc: 'Fine-tuned for code. Huge bonus against Coding requests, average everywhere else.',
  },
  srv_frontier: {
    id: 'srv_frontier',
    name: 'Frontier Server',
    kind: 'server',
    cost: 195,
    range: 3.3,
    color: 0xc792ea,
    accent: 0xf0d9ff,
    quality: 93,
    speed: 26,
    spec: 'reasoning',
    powerDraw: 6,
    heat: 6,
    targets: 2,
    tagline: 'Expensive · slow · brilliant',
    desc: 'The biggest model. Answers Reasoning and Enterprise correctly — but drinks power and runs hot.',
  },
  router: {
    id: 'router',
    name: 'Router',
    kind: 'router',
    cost: 90,
    range: 3.6,
    color: 0xff9f43,
    accent: 0xffd9a8,
    routeBonus: 0.45,
    powerDraw: 1,
    heat: 1,
    tagline: 'Smart traffic assignment',
    desc: 'Reads each request and steers it to the right server. Boosts matched servers and is the heart of a smart build.',
  },
  cache: {
    id: 'cache',
    name: 'Cache Server',
    kind: 'cache',
    cost: 75,
    range: 3.0,
    color: 0x4fd6c4,
    accent: 0xc7fff5,
    cacheChance: 0.5,
    powerDraw: 1,
    heat: 1,
    tagline: 'Buffs servers · instant hits',
    desc: 'Aura: gives Serving Towers in range a chance to instantly answer cacheable traffic (Chat, Long Context, Bots). Overlap it with your servers.',
  },
  safety: {
    id: 'safety',
    name: 'Safety Gate',
    kind: 'safety',
    cost: 85,
    range: 2.9,
    color: 0xff6b9d,
    accent: 0xffc8dd,
    safetyRate: 1.35,
    powerDraw: 1,
    heat: 1,
    tagline: 'Clears risky requests',
    desc: 'Neutralizes Jailbreak risk for any request passing through. Place it before the core.',
  },
  power: {
    id: 'power',
    name: 'Power Plant',
    kind: 'power',
    cost: 70,
    range: 0,
    color: 0xffb454,
    accent: 0xffe0a8,
    power: 13,
    tagline: '+13 power capacity',
    desc: 'Raises electricity capacity. Without enough power your GPUs brown out and go dark.',
  },
  cooling: {
    id: 'cooling',
    name: 'Cooling Tower',
    kind: 'cooling',
    cost: 70,
    range: 0,
    color: 0x59c2ff,
    accent: 0xc4ecff,
    cooling: 13,
    tagline: '+13 cooling capacity',
    desc: 'Raises heat capacity. Over the limit, every GPU thermally throttles and serves slower.',
  },
  lab: {
    id: 'lab',
    name: 'Training Lab',
    kind: 'lab',
    cost: 120,
    range: 0,
    color: 0xb084f5,
    accent: 0xe6d6ff,
    tagline: 'Unlocks the tech tree',
    desc: 'Required to train. Improves Data yield and opens the four research paths between waves.',
  },
}

export const BUILD_ORDER = [
  'srv_small',
  'srv_general',
  'srv_coding',
  'srv_frontier',
  'router',
  'cache',
  'safety',
  'power',
  'cooling',
  'lab',
]

/* ------------------------------------------------------------------ *
 *  WAVES — the escalating campaign.                                  *
 * ------------------------------------------------------------------ */

export const WAVES: WaveDef[] = [
  {
    name: 'Launch Day',
    brief: 'Mostly Simple Chat. Welcome to production.',
    teaches: 'Place a server near the lane and watch it serve.',
    clearBonus: 60,
    groups: [
      { typeId: 'chat', count: 10, interval: 1.1, delay: 0.5 },
      { typeId: 'chat', count: 6, interval: 0.8, delay: 9 },
    ],
  },
  {
    name: 'Coding Boom',
    brief: 'A coding-assistant trend hits. Correctness matters now.',
    teaches: 'Quality below a request’s complexity ships a bad answer.',
    clearBonus: 80,
    groups: [
      { typeId: 'chat', count: 8, interval: 1.0, delay: 0.5 },
      { typeId: 'code', count: 10, interval: 1.2, delay: 4 },
      { typeId: 'code', count: 6, interval: 0.9, delay: 16, workMul: 1.1 },
    ],
  },
  {
    name: 'Mixed Traffic',
    brief: 'Chat, code, and long context — all at once.',
    teaches: 'One model can’t do it all. Spread coverage and add a Router.',
    clearBonus: 110,
    groups: [
      { typeId: 'chat', count: 10, interval: 0.8, delay: 0 },
      { typeId: 'code', count: 8, interval: 1.1, delay: 3 },
      { typeId: 'long', count: 7, interval: 1.3, delay: 8 },
      { typeId: 'code', count: 5, interval: 1.0, delay: 18 },
    ],
  },
  {
    name: 'Jailbreak Raid',
    brief: 'Malicious prompts hide among real users.',
    teaches: 'A Safety Gate before the core, or Trust bleeds.',
    clearBonus: 120,
    groups: [
      { typeId: 'chat', count: 8, interval: 0.7, delay: 0 },
      { typeId: 'jail', count: 8, interval: 1.3, delay: 4 },
      { typeId: 'jail', count: 6, interval: 1.0, delay: 16 },
      { typeId: 'code', count: 5, interval: 1.2, delay: 10 },
    ],
  },
  {
    name: 'Enterprise Contract',
    brief: 'Fewer requests, brutal SLA, big money.',
    teaches: 'Priority and reliability beat raw volume.',
    clearBonus: 150,
    groups: [
      { typeId: 'ent', count: 8, interval: 2.0, delay: 1 },
      { typeId: 'reason', count: 6, interval: 1.8, delay: 6 },
      { typeId: 'ent', count: 5, interval: 1.6, delay: 18, workMul: 1.1 },
    ],
  },
  {
    name: 'Viral Spike',
    brief: 'An app integration goes viral. Volume explodes.',
    teaches: 'Cache and throughput, not infinite GPUs.',
    clearBonus: 170,
    groups: [
      { typeId: 'bot', count: 30, interval: 0.32, delay: 0 },
      { typeId: 'chat', count: 16, interval: 0.5, delay: 3 },
      { typeId: 'long', count: 8, interval: 1.1, delay: 10 },
      { typeId: 'bot', count: 24, interval: 0.3, delay: 16 },
    ],
  },
  {
    name: 'Heavy Reasoning',
    brief: 'The hard stuff. Frontier-grade or bust.',
    teaches: 'Scale and efficiency must both be funded.',
    clearBonus: 200,
    groups: [
      { typeId: 'reason', count: 10, interval: 1.3, delay: 0, workMul: 1.15 },
      { typeId: 'ent', count: 7, interval: 1.7, delay: 6 },
      { typeId: 'reason', count: 8, interval: 1.1, delay: 16, workMul: 1.2 },
    ],
  },
  {
    name: 'Code Review Crunch',
    brief: 'A wall of pull requests. Ship correct code, fast.',
    teaches: 'Coding Servers (or pretraining) carry correctness-heavy waves.',
    clearBonus: 230,
    groups: [
      { typeId: 'code', count: 14, interval: 0.8, delay: 0 },
      { typeId: 'code', count: 10, interval: 0.9, delay: 10, workMul: 1.15 },
      { typeId: 'reason', count: 5, interval: 1.6, delay: 18 },
    ],
  },
  {
    name: 'The Long Haul',
    brief: 'Endless long-context documents. Token costs balloon.',
    teaches: 'Cache + KV Cache make Long Context survivable.',
    clearBonus: 250,
    groups: [
      { typeId: 'long', count: 14, interval: 1.0, delay: 0 },
      { typeId: 'chat', count: 12, interval: 0.7, delay: 4 },
      { typeId: 'long', count: 9, interval: 1.1, delay: 16, workMul: 1.2 },
    ],
  },
  {
    name: 'Adversarial Surge',
    brief: 'Coordinated jailbreaks woven through real traffic.',
    teaches: 'Scale Safety with RLHF and Red-teaming, not just one gate.',
    clearBonus: 280,
    groups: [
      { typeId: 'jail', count: 12, interval: 0.9, delay: 0 },
      { typeId: 'chat', count: 10, interval: 0.7, delay: 3 },
      { typeId: 'code', count: 8, interval: 1.0, delay: 10 },
      { typeId: 'jail', count: 9, interval: 0.8, delay: 18 },
    ],
  },
  {
    name: 'Black Friday',
    brief: 'Bot armies and shoppers. The biggest volume yet.',
    teaches: 'Caches, batching and rate-limits beat raw GPU spend.',
    clearBonus: 320,
    groups: [
      { typeId: 'bot', count: 40, interval: 0.26, delay: 0 },
      { typeId: 'chat', count: 18, interval: 0.45, delay: 4 },
      { typeId: 'ent', count: 6, interval: 1.8, delay: 12 },
      { typeId: 'bot', count: 30, interval: 0.28, delay: 18 },
    ],
  },
  {
    name: 'Research Benchmark',
    brief: 'Brutal reasoning problems for the leaderboard.',
    teaches: 'Max Quality via Pretraining; Frontier is mandatory.',
    clearBonus: 360,
    groups: [
      { typeId: 'reason', count: 12, interval: 1.1, delay: 0, workMul: 1.2 },
      { typeId: 'reason', count: 10, interval: 1.0, delay: 12, workMul: 1.3 },
      { typeId: 'ent', count: 6, interval: 1.6, delay: 20 },
    ],
  },
  {
    name: 'Multi-Tenant Cloud',
    brief: 'Every customer, every request type, at once.',
    teaches: 'Only a well-tuned Router keeps a 7-type mix afloat.',
    clearBonus: 400,
    groups: [
      { typeId: 'chat', count: 12, interval: 0.7, delay: 0 },
      { typeId: 'code', count: 9, interval: 1.0, delay: 3 },
      { typeId: 'long', count: 8, interval: 1.1, delay: 7 },
      { typeId: 'reason', count: 7, interval: 1.2, delay: 12 },
      { typeId: 'jail', count: 7, interval: 1.1, delay: 16 },
      { typeId: 'ent', count: 6, interval: 1.5, delay: 22 },
    ],
  },
  {
    name: 'Security Audit',
    brief: 'Jailbreaks under enterprise SLA, with auditors watching.',
    teaches: 'Safety and reliability at the same time — no slack.',
    clearBonus: 440,
    groups: [
      { typeId: 'jail', count: 14, interval: 0.8, delay: 0 },
      { typeId: 'ent', count: 8, interval: 1.5, delay: 6 },
      { typeId: 'reason', count: 7, interval: 1.3, delay: 14 },
      { typeId: 'jail', count: 10, interval: 0.7, delay: 20 },
    ],
  },
  {
    name: 'The Scaling Wall',
    brief: 'Fewer requests, each one enormous. Pure compute.',
    teaches: 'Scaling laws bite: params, data and serving must all scale.',
    clearBonus: 500,
    groups: [
      { typeId: 'reason', count: 8, interval: 1.5, delay: 0, workMul: 1.4 },
      { typeId: 'ent', count: 7, interval: 1.6, delay: 8, workMul: 1.3 },
      { typeId: 'code', count: 8, interval: 1.2, delay: 14, workMul: 1.3 },
      { typeId: 'reason', count: 6, interval: 1.4, delay: 22, workMul: 1.5 },
    ],
  },
  {
    name: 'Sustained Load',
    brief: 'No bursts — just a relentless, unbroken stream.',
    teaches: 'Endurance: throughput and economy over a long wave.',
    clearBonus: 540,
    groups: [
      { typeId: 'chat', count: 16, interval: 0.6, delay: 0 },
      { typeId: 'code', count: 10, interval: 0.9, delay: 6 },
      { typeId: 'long', count: 10, interval: 1.0, delay: 12 },
      { typeId: 'reason', count: 8, interval: 1.2, delay: 20 },
      { typeId: 'ent', count: 6, interval: 1.6, delay: 28 },
      { typeId: 'code', count: 9, interval: 0.9, delay: 34 },
    ],
  },
  {
    name: 'Spike Storm',
    brief: 'Volume floods alternating with reasoning spikes.',
    teaches: 'Build for both extremes — cheap throughput and raw quality.',
    clearBonus: 580,
    groups: [
      { typeId: 'bot', count: 32, interval: 0.24, delay: 0 },
      { typeId: 'reason', count: 6, interval: 1.4, delay: 6, workMul: 1.3 },
      { typeId: 'bot', count: 32, interval: 0.24, delay: 12 },
      { typeId: 'ent', count: 6, interval: 1.5, delay: 18 },
      { typeId: 'reason', count: 7, interval: 1.2, delay: 24, workMul: 1.3 },
    ],
  },
  {
    name: 'Enterprise Megadeal',
    brief: 'A flood of high-value contracts with merciless SLAs.',
    teaches: 'One timeout is catastrophic — over-provision the priority lane.',
    clearBonus: 680,
    groups: [
      { typeId: 'ent', count: 12, interval: 1.2, delay: 0 },
      { typeId: 'reason', count: 8, interval: 1.3, delay: 8, workMul: 1.2 },
      { typeId: 'ent', count: 10, interval: 1.0, delay: 18, workMul: 1.15 },
      { typeId: 'ent', count: 8, interval: 1.1, delay: 28, workMul: 1.2 },
    ],
  },
  {
    name: 'Jailbreak Apocalypse',
    brief: 'A relentless abuse campaign trying to break Trust.',
    teaches: 'Maxed Safety, layered gates, and Red-teaming or bust.',
    clearBonus: 760,
    groups: [
      { typeId: 'jail', count: 18, interval: 0.6, delay: 0 },
      { typeId: 'chat', count: 12, interval: 0.6, delay: 4 },
      { typeId: 'jail', count: 14, interval: 0.6, delay: 14 },
      { typeId: 'code', count: 8, interval: 1.0, delay: 20 },
      { typeId: 'jail', count: 12, interval: 0.7, delay: 26 },
    ],
  },
  {
    name: 'Singularity Night',
    brief: 'BOSS — everything, escalating, until dawn. Survive it.',
    teaches: 'The whole platform at maximum pressure.',
    clearBonus: 1200,
    groups: [
      { typeId: 'bot', count: 36, interval: 0.24, delay: 0 },
      { typeId: 'chat', count: 14, interval: 0.5, delay: 2 },
      { typeId: 'code', count: 10, interval: 0.9, delay: 6 },
      { typeId: 'jail', count: 12, interval: 0.9, delay: 10 },
      { typeId: 'long', count: 9, interval: 1.1, delay: 14 },
      { typeId: 'reason', count: 10, interval: 1.1, delay: 20, workMul: 1.3 },
      { typeId: 'ent', count: 9, interval: 1.3, delay: 28, workMul: 1.25 },
      { typeId: 'reason', count: 8, interval: 1.0, delay: 36, workMul: 1.4 },
      { typeId: 'jail', count: 10, interval: 0.7, delay: 42 },
    ],
  },
]

/* ------------------------------------------------------------------ *
 *  TECH TREE — four competing paths sharing Cash + Data.             *
 * ------------------------------------------------------------------ */

export const UPGRADES: UpgradeDef[] = [
  // Scale
  {
    id: 'scale_pretrain',
    path: 'scale',
    name: 'Pretraining',
    cashCost: 120,
    dataCost: 8,
    maxLevel: 3,
    desc: '+8 Quality to every server. Bigger base model, better answers.',
  },
  {
    id: 'scale_throughput',
    path: 'scale',
    name: 'Bigger Racks',
    cashCost: 140,
    dataCost: 6,
    maxLevel: 3,
    desc: '+12% compute speed to every server.',
  },
  // Efficiency
  {
    id: 'eff_quant',
    path: 'efficiency',
    name: 'Quantization',
    cashCost: 110,
    dataCost: 6,
    maxLevel: 2,
    desc: '-25% power draw on every server. Slightly cheaper to run.',
  },
  {
    id: 'eff_distill',
    path: 'efficiency',
    name: 'Distillation',
    cashCost: 120,
    dataCost: 8,
    maxLevel: 2,
    desc: 'Small Servers gain +30% speed — cheap models punch up.',
  },
  {
    id: 'eff_spec',
    path: 'efficiency',
    name: 'Speculative Decoding',
    cashCost: 160,
    dataCost: 10,
    maxLevel: 2,
    desc: 'Frontier Servers gain +35% speed. Small model drafts, big model verifies.',
  },
  // Safety
  {
    id: 'saf_rlhf',
    path: 'safety',
    name: 'RLHF',
    cashCost: 120,
    dataCost: 8,
    maxLevel: 2,
    desc: '+40% Safety Gate clear rate and -30% unsafe-answer penalty.',
  },
  {
    id: 'saf_redteam',
    path: 'safety',
    name: 'Red-teaming',
    cashCost: 130,
    dataCost: 9,
    maxLevel: 2,
    desc: 'Jailbreaks arrive 30% less risky — easier to neutralize.',
  },
  // Product
  {
    id: 'prod_route',
    path: 'product',
    name: 'Cost-Aware Routing',
    cashCost: 120,
    dataCost: 7,
    maxLevel: 2,
    desc: '+40% Router bonus. Matched servers serve much faster.',
  },
  {
    id: 'prod_cache',
    path: 'product',
    name: 'KV Cache',
    cashCost: 110,
    dataCost: 7,
    maxLevel: 2,
    desc: '+20% Cache hit chance and cheaper Long Context.',
  },
  {
    id: 'prod_batch',
    path: 'product',
    name: 'Continuous Batching',
    cashCost: 170,
    dataCost: 11,
    maxLevel: 1,
    desc: 'Every server processes one extra request at once.',
  },
]

export const UPGRADE_MAP: Record<string, UpgradeDef> = Object.fromEntries(UPGRADES.map((u) => [u.id, u]))

export const TECH_PATHS = [
  { id: 'scale', name: 'Scale', color: COLORS.danger, theme: 'Bigger models, more throughput.' },
  { id: 'efficiency', name: 'Efficiency', color: COLORS.cooling, theme: 'Do more with less power.' },
  { id: 'safety', name: 'Safety', color: 0xff6b9d, theme: 'Resist abuse, keep Trust.' },
  { id: 'product', name: 'Product', color: COLORS.warn, theme: 'Routing, cache, system design.' },
] as const

/* ------------------------------------------------------------------ *
 *  INCIDENTS — between-wave events that force adaptation.             *
 * ------------------------------------------------------------------ */

export const INCIDENTS: IncidentDef[] = [
  {
    id: 'inc_power',
    name: 'Power-Price Spike',
    icon: '⚡',
    mods: { powerPrice: 2.0 },
    desc: 'Energy markets spike. Running GPUs costs 2× cash this wave.',
  },
  {
    id: 'inc_cooling',
    name: 'Cooling Failure',
    icon: '❄',
    mods: { coolingCap: 0.6 },
    desc: 'A chiller fails. Cooling capacity drops 40% this wave — expect throttling.',
  },
  {
    id: 'inc_gpu',
    name: 'GPU Shortage',
    icon: '▣',
    mods: { buildCost: 1.5 },
    desc: 'Supply chain crunch. New buildings cost 50% more this wave.',
  },
  {
    id: 'inc_audit',
    name: 'Regulatory Audit',
    icon: '⚖',
    mods: { safetyDamage: 2.0 },
    desc: 'Auditors are watching. Unsafe answers cost 2× Trust this wave.',
  },
  {
    id: 'inc_viral',
    name: 'Viral Integration',
    icon: '↗',
    mods: { volume: 1.35, reward: 1.3 },
    good: true,
    desc: 'You went viral! +35% request volume but +30% reward this wave.',
  },
  {
    id: 'inc_demo',
    name: 'Enterprise Demo',
    icon: '★',
    mods: { reward: 1.5 },
    good: true,
    desc: 'A big client is evaluating. All rewards +50% this wave — do not disappoint.',
  },
  {
    id: 'inc_contam',
    name: 'Dataset Contamination',
    icon: '☠',
    mods: {},
    desc: 'Bad data slipped in. You lose a chunk of stored Data.',
    instant: (s) => {
      s.data = Math.max(0, Math.floor(s.data * 0.5))
    },
  },
]
